{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-paletteer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paletteer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paletteer/paletteer_{{ version }}.tar.gz
  sha256: a7d2553cc1241add9f2515c1dec4d8f041fdea3141b28a525b15bafb5821496e

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-gameofthrones >=1.0.0
    - r-ggthemes >=4.0.0
    - r-harrypotter >=2.1.0
    - r-jcolors
    - r-oompabase
    - r-palr
    - r-pals
    - r-rlang
    - r-scico
    - r-viridislite
    - r-glue
    - r-rematch2
    - r-rstudioapi
    - r-prismatic
  run:
    - r-base
    - r-gameofthrones >=1.0.0
    - r-ggthemes >=4.0.0
    - r-harrypotter >=2.1.0
    - r-jcolors
    - r-oompabase
    - r-palr
    - r-pals
    - r-rlang
    - r-scico
    - r-viridislite
    - r-glue
    - r-rematch2
    - r-rstudioapi
    - r-prismatic

test:
  commands:
    - $R -e "library('paletteer')"           # [not win]
    - "\"%R%\" -e \"library('paletteer')\""  # [win]

about:
  home: https://github.com/EmilHvitfeldt/paletteer
  license: GPL-3.0-only
  summary: The choices of color palettes in R can be quite overwhelming with  palettes spread over many packages with many different API's. This packages aims to collect all color palettes across the R ecosystem under the same package with a streamlined API.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: paletteer
# Version: 0.2.1
# Title: Comprehensive Collection of Color Palettes
# Description: The choices of color palettes in R can be quite overwhelming with  palettes spread over many packages with many different API's. This packages aims to collect all color palettes across the R ecosystem under the same package with a streamlined API.
# Author: See AUTHORS file.
# Maintainer: Emil Hvitfeldt <emilhhvitfeldt@gmail.com>
# License: GPL-3
# Copyright: See LICENSE.note file.
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/EmilHvitfeldt/paletteer
# BugReports: https://github.com/EmilHvitfeldt/paletteer/issues
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Imports: gameofthrones (>= 1.0.0), ggthemes (>= 4.0.0), jcolors, oompaBase, harrypotter (>= 2.1.0), palr, pals, scico, viridisLite, rlang
# Suggests: covr, testthat, ggplot2, knitr, rmarkdown
# NeedsCompilation: no
# Packaged: 2019-02-10 19:29:13 UTC; emilhvitfeldthansen
# Repository: CRAN
# Date/Publication: 2019-02-13 22:00:08 UTC
