appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UJ9j4Ulmml1r7G3MlEbHD2+1/JJtX7Fy5Nk1E/gmLMMAV/ooP69O62yoCiLi1n8r/Eo6/UVyFu4rRDOntH3vrZR+pZoATTNxlfldx/gYnfxxnjEWIjDuZ3EaCjPLtlPSRz/Ba8RMeQCtKgQ2xE7iQoQ+SWGe/DUVMwpD8ZAz5exGDNw68OzmF091PL28k+3vSZVujWfwDVMQ8+CB2Jk2q0fsDyXQVxGWAwQmFDCc53M9vydNgwjJckP9CWWsVYehS7XvRF3yxSwRTJ0Ne+rBcmfsVWcjB0wVuYmszZiLc90JINCJMtNBfL9JfzbaJAYF/lCFm2jRCO5rcS7zgyAC3q6DKZ/AmVnV5EF6O3GlAhGI+aoi4ffHQ0mfnm6ew+aecQ643qfEKjlsZ2kneShHgHR+ajSdAEYUhKx5ZU24HWmV+NHWeds/H5nwaQHHhq4YrpFgkFExMEdedMslOBmYGQKmhzReTcGw9xk2nVXq7KpzyiLZwMPUeGR9wdXWq8nXmNv8cCLXl0Nxqqf0cKqPHdGvj1rG8dQS+fUfrH531kBdq0W3osuAX4AvAty/tM7WUwEO2UxqOs9FSuKrb/8t0o9a1K3L8d5oRQBU6h3HGNZMqQtQxMabelq/kqgl831q43oYGnFCscVj6Foxoav+hM95JXmrYloRZAX8yuy3+eE=}
bot:
  automerge: true
